const horrorMovies = [
    { title: "The Cabinet of Dr. Caligari", genre: "classic" },
    { title: "Nosferatu", genre: "classic" },
    { title: "Dracula", genre: "classic" },
    { title: "Frankenstein", genre: "classic" },
    { title: "The Mummy", genre: "classic" },
    { title: "The Invisible Man", genre: "classic" },
    { title: "The Wolf Man", genre: "classic" },
    { title: "Creature from the Black Lagoon", genre: "classic" },
    { title: "Cat People", genre: "classic" },
    { title: "I Walked with a Zombie", genre: "classic" },
    { title: "The Body Snatcher", genre: "classic" },
    { title: "House of Wax", genre: "classic" },
    { title: "The Thing from Another World", genre: "classic" },
    { title: "Invasion of the Body Snatchers", genre: "classic" },
    { title: "The Fly", genre: "classic" },
    { title: "The Haunting", genre: "classic" },
    { title: "House on Haunted Hill", genre: "classic" },
    { title: "Psycho", genre: "classic" },
    { title: "The Birds", genre: "classic" },
    { title: "Rosemary's Baby", genre: "classic" },
    { title: "Night of the Living Dead", genre: "classic" },
    { title: "The Wicker Man", genre: "classic" },
    { title: "The Texas Chain Saw Massacre", genre: "classic" },
    { title: "Black Christmas", genre: "classic" },
    { title: "Carrie", genre: "classic" },
    { title: "Suspiria", genre: "classic" },
    { title: "Dawn of the Dead", genre: "classic" },
    { title: "The Omen", genre: "classic" },
    { title: "Jaws", genre: "classic" },
    { title: "Alien", genre: "classic" },
    { title: "Halloween", genre: "classic" },
    { title: "The Shining", genre: "classic" },
    { title: "The Evil Dead", genre: "classic" },
    { title: "A Nightmare on Elm Street", genre: "classic" },
    { title: "The Lost Boys", genre: "classic" },
    { title: "The Fog", genre: "classic" },
    { title: "The Changeling", genre: "classic" },
    { title: "The Amityville Horror", genre: "classic" },
    { title: "The Howling", genre: "classic" },
    { title: "The Return of the Living Dead", genre: "classic" },
    { title: "Child's Play", genre: "classic" },
    { title: "Hellraiser", genre: "classic" },
    { title: "Poltergeist", genre: "classic" },
    { title: "Gremlins", genre: "classic" },
    { title: "The Blob", genre: "classic" },
    { title: "Christine", genre: "classic" },
    { title: "The Exorcist", genre: "classic" },
    { title: "The Exorcist III", genre: "classic" },
    { title: "The Silence of the Lambs", genre: "classic" },
    { title: "Candyman", genre: "classic" },
    { title: "Misery", genre: "classic" },
    { title: "Jacob's Ladder", genre: "classic" },
    { title: "Tremors", genre: "classic" },
    { title: "Army of Darkness", genre: "classic" },
    { title: "Bram Stoker's Dracula", genre: "classic" },
    { title: "Interview with the Vampire", genre: "classic" },
    { title: "Scream", genre: "classic" },
    { title: "The Craft", genre: "classic" },
    { title: "From Dusk Till Dawn", genre: "classic" },
    { title: "Event Horizon", genre: "classic" },
    { title: "The Faculty", genre: "classic" },
    { title: "Sleepy Hollow", genre: "classic" },
    { title: "The Blair Witch Project", genre: "classic" },
    { title: "Friday the 13th", genre: "slasher" },
    { title: "Friday the 13th Part 2", genre: "slasher" },
    { title: "Friday the 13th Part III", genre: "slasher" },
    { title: "Friday the 13th: The Final Chapter", genre: "slasher" },
    { title: "Friday the 13th Part VI: Jason Lives", genre: "slasher" },
    { title: "Friday the 13th Part VII: The New Blood", genre: "slasher" },
    { title: "Friday the 13th Part VIII: Jason Takes Manhattan", genre: "slasher" },
    { title: "Jason Goes to Hell: The Final Friday", genre: "slasher" },
    { title: "Freddy vs. Jason", genre: "slasher" },
    { title: "A Nightmare on Elm Street 2: Freddy's Revenge", genre: "slasher" },
    { title: "A Nightmare on Elm Street 3: Dream Warriors", genre: "slasher" },
    { title: "A Nightmare on Elm Street 4: The Dream Master", genre: "slasher" },
    { title: "A Nightmare on Elm Street 5: The Dream Child", genre: "slasher" },
    { title: "Wes Craven's New Nightmare", genre: "slasher" },
    { title: "Halloween II", genre: "slasher" },
    { title: "Halloween III: Season of the Witch", genre: "slasher" },
    { title: "Halloween 4: The Return of Michael Myers", genre: "slasher" },
    { title: "Halloween 5: The Revenge of Michael Myers", genre: "slasher" },
    { title: "Halloween H20", genre: "slasher" },
    { title: "Halloween: Resurrection", genre: "slasher" },
    { title: "Halloween (2007)", genre: "slasher" },
    { title: "Halloween II (2009)", genre: "slasher" },
    { title: "Halloween (2018)", genre: "slasher" },
    { title: "Halloween Kills", genre: "slasher" },
    { title: "Halloween Ends", genre: "slasher" },
    { title: "Scream 2", genre: "slasher" },
    { title: "Scream 3", genre: "slasher" },
    { title: "Scream 4", genre: "slasher" },
    { title: "Scream (2022)", genre: "slasher" },
    { title: "Scream VI", genre: "slasher" },
    { title: "I Know What You Did Last Summer", genre: "slasher" },
    { title: "I Still Know What You Did Last Summer", genre: "slasher" },
    { title: "Urban Legend", genre: "slasher" },
    { title: "Urban Legends: Final Cut", genre: "slasher" },
    { title: "Final Destination", genre: "slasher" },
    { title: "Final Destination 2", genre: "slasher" },
    { title: "Final Destination 3", genre: "slasher" },
    { title: "The Final Destination", genre: "slasher" },
    { title: "Final Destination 5", genre: "slasher" },
    { title: "Final Destination: Bloodlines", genre: "slasher" },
    { title: "Texas Chainsaw Massacre (2003)", genre: "slasher" },
    { title: "The Texas Chainsaw Massacre: The Beginning", genre: "slasher" },
    { title: "Hatchet", genre: "slasher" },
    { title: "Hatchet II", genre: "slasher" },
    { title: "Hatchet III", genre: "slasher" },
    { title: "Hatchet IV: Victor Crowley", genre: "slasher" },
    { title: "Terrifier", genre: "slasher" },
    { title: "Terrifier 2", genre: "slasher" },
    { title: "Terrifier 3", genre: "slasher" },
    { title: "Pearl", genre: "slasher" },
    { title: "X", genre: "slasher" },
    { title: "Thanksgiving", genre: "slasher" },
    { title: "Thanksgiving (2023)", genre: "slasher" },
    { title: "Freaky", genre: "slasher" },
    { title: "Fear Street Part One: 1994", genre: "slasher" },
    { title: "Fear Street Part Two: 1978", genre: "slasher" },
    { title: "Fear Street Part Three: 1666", genre: "slasher" },
    { title: "Ready or Not", genre: "slasher" },
    { title: "You're Next", genre: "slasher" },
    { title: "The Strangers", genre: "slasher" },
    { title: "The Strangers: Prey at Night", genre: "slasher" },
    { title: "Black Christmas (2006)", genre: "slasher" },
    { title: "Black Christmas (2019)", genre: "slasher" },
    { title: "Prom Night", genre: "slasher" },
    { title: "My Bloody Valentine", genre: "slasher" },
    { title: "Sleepaway Camp", genre: "slasher" },
    { title: "Maniac", genre: "slasher" },
    { title: "The Prowler", genre: "slasher" },
    { title: "The Burning", genre: "slasher" },
    { title: "The House on Sorority Row", genre: "slasher" },
    { title: "Happy Death Day", genre: "slasher" },
    { title: "Happy Death Day 2U", genre: "slasher" },
    { title: "Behind the Mask: The Rise of Leslie Vernon", genre: "slasher" },
    { title: "Stage Fright", genre: "slasher" },
    { title: "The Collector", genre: "slasher" },
    { title: "The Collection", genre: "slasher" },
    { title: "Hell Fest", genre: "slasher" },
    { title: "The Conjuring", genre: "supernatural" },
    { title: "The Conjuring 2", genre: "supernatural" },
    { title: "The Conjuring: The Devil Made Me Do It", genre: "supernatural" },
    { title: "Annabelle", genre: "supernatural" },
    { title: "Annabelle: Creation", genre: "supernatural" },
    { title: "Annabelle Comes Home", genre: "supernatural" },
    { title: "The Nun", genre: "supernatural" },
    { title: "The Nun II", genre: "supernatural" },
    { title: "Insidious", genre: "supernatural" },
    { title: "Insidious: Chapter 2", genre: "supernatural" },
    { title: "Insidious: Chapter 3", genre: "supernatural" },
    { title: "Insidious: The Last Key", genre: "supernatural" },
    { title: "Insidious: The Red Door", genre: "supernatural" },
    { title: "Sinister", genre: "supernatural" },
    { title: "Sinister 2", genre: "supernatural" },
    { title: "The Ring", genre: "supernatural" },
    { title: "The Ring Two", genre: "supernatural" },
    { title: "Ringu", genre: "supernatural" },
    { title: "The Grudge", genre: "supernatural" },
    { title: "The Grudge 2", genre: "supernatural" },
    { title: "Ju-On: The Grudge", genre: "supernatural" },
    { title: "It", genre: "supernatural" },
    { title: "It Chapter Two", genre: "supernatural" },
    { title: "The Others", genre: "supernatural" },
    { title: "The Sixth Sense", genre: "supernatural" },
    { title: "The Woman in Black", genre: "supernatural" },
    { title: "The Woman in Black 2: Angel of Death", genre: "supernatural" },
    { title: "Oculus", genre: "supernatural" },
    { title: "Ouija", genre: "supernatural" },
    { title: "Ouija: Origin of Evil", genre: "supernatural" },
    { title: "Lights Out", genre: "supernatural" },
    { title: "The Autopsy of Jane Doe", genre: "supernatural" },
    { title: "The Exorcism of Emily Rose", genre: "supernatural" },
    { title: "The Taking of Deborah Logan", genre: "supernatural" },
    { title: "The Possession", genre: "supernatural" },
    { title: "The Possession of Michael King", genre: "supernatural" },
    { title: "The Dark and the Wicked", genre: "supernatural" },
    { title: "The Vigil", genre: "supernatural" },
    { title: "The Empty Man", genre: "supernatural" },
    { title: "Smile", genre: "supernatural" },
    { title: "Smile 2", genre: "supernatural" },
    { title: "Talk to Me", genre: "supernatural" },
    { title: "The Black Phone", genre: "supernatural" },
    { title: "The Boogeyman", genre: "supernatural" },
    { title: "Evil Dead Rise", genre: "supernatural" },
    { title: "Drag Me to Hell", genre: "supernatural" },
    { title: "Dead Silence", genre: "supernatural" },
    { title: "1408", genre: "supernatural" },
    { title: "The Skeleton Key", genre: "supernatural" },
    { title: "The Devil's Backbone", genre: "supernatural" },
    { title: "The Orphanage", genre: "supernatural" },
    { title: "The Innocents", genre: "supernatural" },
    { title: "His House", genre: "supernatural" },
    { title: "Host", genre: "supernatural" },
    { title: "The Night House", genre: "supernatural" },
    { title: "The Lodge", genre: "supernatural" },
    { title: "The Ritual", genre: "supernatural" },
    { title: "The Medium", genre: "supernatural" },
    { title: "Veronica", genre: "supernatural" },
    { title: "The Wailing", genre: "supernatural" },
    { title: "Incantation", genre: "supernatural" },
    { title: "The Pope's Exorcist", genre: "supernatural" },
    { title: "Late Night with the Devil", genre: "supernatural" },
    { title: "The First Omen", genre: "supernatural" },
    { title: "Abigail", genre: "supernatural" },
    { title: "The Watchers", genre: "supernatural" },
    { title: "Oddity", genre: "supernatural" },
    { title: "Longlegs", genre: "supernatural" },
    { title: "Get Out", genre: "psychological" },
    { title: "Us", genre: "psychological" },
    { title: "Nope", genre: "psychological" },
    { title: "Hereditary", genre: "psychological" },
    { title: "Midsommar", genre: "psychological" },
    { title: "The Witch", genre: "psychological" },
    { title: "The Lighthouse", genre: "psychological" },
    { title: "Black Swan", genre: "psychological" },
    { title: "The Invitation", genre: "psychological" },
    { title: "Enemy", genre: "psychological" },
    { title: "Shutter Island", genre: "psychological" },
    { title: "The Machinist", genre: "psychological" },
    { title: "American Psycho", genre: "psychological" },
    { title: "The Killing of a Sacred Deer", genre: "psychological" },
    { title: "The Babadook", genre: "psychological" },
    { title: "Saint Maud", genre: "psychological" },
    { title: "The Lodge", genre: "psychological" },
    { title: "The Perfection", genre: "psychological" },
    { title: "Cam", genre: "psychological" },
    { title: "Creep", genre: "psychological" },
    { title: "Creep 2", genre: "psychological" },
    { title: "The Platform", genre: "psychological" },
    { title: "The Invisible Man (2020)", genre: "psychological" },
    { title: "Barbarian", genre: "psychological" },
    { title: "Fresh", genre: "psychological" },
    { title: "Watcher", genre: "psychological" },
    { title: "Speak No Evil", genre: "psychological" },
    { title: "Speak No Evil (2024)", genre: "psychological" },
    { title: "The Menu", genre: "psychological" },
    { title: "Infinity Pool", genre: "psychological" },
    { title: "Possessor", genre: "psychological" },
    { title: "The Skin I Live In", genre: "psychological" },
    { title: "Funny Games", genre: "psychological" },
    { title: "Funny Games U.S.", genre: "psychological" },
    { title: "The House That Jack Built", genre: "psychological" },
    { title: "Mother!", genre: "psychological" },
    { title: "Climax", genre: "psychological" },
    { title: "Raw", genre: "psychological" },
    { title: "Titane", genre: "psychological" },
    { title: "Swallow", genre: "psychological" },
    { title: "The Neon Demon", genre: "psychological" },
    { title: "Perfect Blue", genre: "psychological" },
    { title: "Audition", genre: "psychological" },
    { title: "Oldboy", genre: "psychological" },
    { title: "Session 9", genre: "psychological" },
    { title: "Frailty", genre: "psychological" },
    { title: "Identity", genre: "psychological" },
    { title: "1408", genre: "psychological" },
    { title: "Secret Window", genre: "psychological" },
    { title: "Cape Fear", genre: "psychological" },
    { title: "The Game", genre: "psychological" },
    { title: "Primal Fear", genre: "psychological" },
    { title: "Se7en", genre: "psychological" },
    { title: "Zodiac", genre: "psychological" },
    { title: "The Silence of the Lambs", genre: "psychological" },
    { title: "The Vanishing", genre: "psychological" },
    { title: "We Need to Talk About Kevin", genre: "psychological" },
    { title: "Vivarium", genre: "psychological" },
    { title: "The One I Love", genre: "psychological" },
    { title: "Coherence", genre: "psychological" },
    { title: "Triangle", genre: "psychological" },
    { title: "The Invitation (2015)", genre: "psychological" },
    { title: "Calibre", genre: "psychological" },
    { title: "The Platform 2", genre: "psychological" },
    { title: "Nocturnal Animals", genre: "psychological" },
    { title: "The Gift", genre: "psychological" },
    { title: "The Gift (2015)", genre: "psychological" },
    { title: "Unsane", genre: "psychological" },
    { title: "Run", genre: "psychological" },
    { title: "Watcher (2022)", genre: "psychological" },
    { title: "Goodnight Mommy", genre: "psychological" },
    { title: "The Night House", genre: "psychological" },
    { title: "Relic", genre: "psychological" },
    { title: "Resurrection", genre: "psychological" },
    { title: "The Thing", genre: "creature" },
    { title: "The Thing (2011)", genre: "creature" },
    { title: "Alien", genre: "creature" },
    { title: "Aliens", genre: "creature" },
    { title: "Alien 3", genre: "creature" },
    { title: "Alien: Resurrection", genre: "creature" },
    { title: "Prometheus", genre: "creature" },
    { title: "Alien: Covenant", genre: "creature" },
    { title: "Predator", genre: "creature" },
    { title: "Predator 2", genre: "creature" },
    { title: "Prey", genre: "creature" },
    { title: "Cloverfield", genre: "creature" },
    { title: "10 Cloverfield Lane", genre: "creature" },
    { title: "The Mist", genre: "creature" },
    { title: "An American Werewolf in London", genre: "creature" },
    { title: "Dog Soldiers", genre: "creature" },
    { title: "The Descent", genre: "creature" },
    { title: "The Descent Part 2", genre: "creature" },
    { title: "The Host", genre: "creature" },
    { title: "Underwater", genre: "creature" },
    { title: "Deep Rising", genre: "creature" },
    { title: "Leviathan", genre: "creature" },
    { title: "Sphere", genre: "creature" },
    { title: "Mimic", genre: "creature" },
    { title: "Mimic 2", genre: "creature" },
    { title: "Mimic 3: Sentinel", genre: "creature" },
    { title: "The Relic", genre: "creature" },
    { title: "Slither", genre: "creature" },
    { title: "Splinter", genre: "creature" },
    { title: "The Void", genre: "creature" },
    { title: "The Ritual", genre: "creature" },
    { title: "The Ruins", genre: "creature" },
    { title: "The Cave", genre: "creature" },
    { title: "Sweetheart", genre: "creature" },
    { title: "Sea Fever", genre: "creature" },
    { title: "Sputnik", genre: "creature" },
    { title: "Life", genre: "creature" },
    { title: "The Cloverfield Paradox", genre: "creature" },
    { title: "No One Will Save You", genre: "creature" },
    { title: "The Faculty", genre: "creature" },
    { title: "The Blob (1988)", genre: "creature" },
    { title: "Pumpkinhead", genre: "creature" },
    { title: "Pumpkinhead II", genre: "creature" },
    { title: "Jeepers Creepers", genre: "creature" },
    { title: "Jeepers Creepers 2", genre: "creature" },
    { title: "Jeepers Creepers 3", genre: "creature" },
    { title: "Jeepers Creepers: Reborn", genre: "creature" },
    { title: "The Monster", genre: "creature" },
    { title: "The Host (2006)", genre: "creature" },
    { title: "The Shape of Water", genre: "creature" },
    { title: "The Lair", genre: "creature" },
    { title: "Black Mountain Side", genre: "creature" },
    { title: "Cold Skin", genre: "creature" },
    { title: "The Hallow", genre: "creature" },
    { title: "The Monster Project", genre: "creature" },
    { title: "The Boogeyman", genre: "creature" },
    { title: "Antlers", genre: "creature" },
    { title: "The Wolfman", genre: "creature" },
    { title: "Werewolves Within", genre: "creature" },
    { title: "Ginger Snaps", genre: "creature" },
    { title: "Ginger Snaps 2", genre: "creature" },
    { title: "Ginger Snaps Back", genre: "creature" },
    { title: "Late Phases", genre: "creature" },
    { title: "The Cursed", genre: "creature" },
    { title: "When Animals Dream", genre: "creature" },
    { title: "The Company of Wolves", genre: "creature" },
    { title: "The Howling", genre: "creature" },
    { title: "28 Days Later", genre: "zombie" },
    { title: "28 Weeks Later", genre: "zombie" },
    { title: "28 Years Later", genre: "zombie" },
    { title: "Train to Busan", genre: "zombie" },
    { title: "Peninsula", genre: "zombie" },
    { title: "World War Z", genre: "zombie" },
    { title: "Shaun of the Dead", genre: "zombie" },
    { title: "Dawn of the Dead", genre: "zombie" },
    { title: "Day of the Dead", genre: "zombie" },
    { title: "Land of the Dead", genre: "zombie" },
    { title: "Diary of the Dead", genre: "zombie" },
    { title: "Survival of the Dead", genre: "zombie" },
    { title: "Army of the Dead", genre: "zombie" },
    { title: "Zombieland", genre: "zombie" },
    { title: "Zombieland: Double Tap", genre: "zombie" },
    { title: "Warm Bodies", genre: "zombie" },
    { title: "Rec", genre: "zombie" },
    { title: "[REC] 2", genre: "zombie" },
    { title: "[REC] 3: Genesis", genre: "zombie" },
    { title: "[REC] 4: Apocalypse", genre: "zombie" },
    { title: "The Girl with All the Gifts", genre: "zombie" },
    { title: "The Cured", genre: "zombie" },
    { title: "The Battery", genre: "zombie" },
    { title: "Pontypool", genre: "zombie" },
    { title: "Ravenous", genre: "zombie" },
    { title: "The Night Eats the World", genre: "zombie" },
    { title: "One Cut of the Dead", genre: "zombie" },
    { title: "Little Monsters", genre: "zombie" },
    { title: "Overlord", genre: "zombie" },
    { title: "Cargo", genre: "zombie" },
    { title: "The Dead Don't Die", genre: "zombie" },
    { title: "Fido", genre: "zombie" },
    { title: "Planet Terror", genre: "zombie" },
    { title: "Resident Evil", genre: "zombie" },
    { title: "Resident Evil: Apocalypse", genre: "zombie" },
    { title: "Resident Evil: Extinction", genre: "zombie" },
    { title: "Resident Evil: Afterlife", genre: "zombie" },
    { title: "Resident Evil: Retribution", genre: "zombie" },
    { title: "Resident Evil: The Final Chapter", genre: "zombie" },
    { title: "Resident Evil: Welcome to Raccoon City", genre: "zombie" },
    { title: "The Sadness", genre: "zombie" },
    { title: "The Horde", genre: "zombie" },
    { title: "The Returned", genre: "zombie" },
    { title: "The Last Days", genre: "zombie" },
    { title: "Maggie", genre: "zombie" },
    { title: "Wyrmwood: Road of the Dead", genre: "zombie" },
    { title: "Wyrmwood: Apocalypse", genre: "zombie" },
    { title: "Dead Snow", genre: "zombie" },
    { title: "Dead Snow 2: Red vs. Dead", genre: "zombie" },
    { title: "Juan of the Dead", genre: "zombie" },
    { title: "Scouts Guide to the Zombie Apocalypse", genre: "zombie" },
    { title: "The Rezort", genre: "zombie" },
    { title: "The Stalled", genre: "zombie" },
    { title: "Blood Quantum", genre: "zombie" },
    { title: "Handling the Undead", genre: "zombie" },
    { title: "Apocalypse Z: The Beginning of the End", genre: "zombie" },
    { title: "The Blair Witch Project", genre: "found-footage" },
    { title: "Paranormal Activity", genre: "found-footage" },
    { title: "Paranormal Activity 2", genre: "found-footage" },
    { title: "Paranormal Activity 3", genre: "found-footage" },
    { title: "Paranormal Activity 4", genre: "found-footage" },
    { title: "Paranormal Activity: The Marked Ones", genre: "found-footage" },
    { title: "Paranormal Activity: The Ghost Dimension", genre: "found-footage" },
    { title: "Paranormal Activity: Next of Kin", genre: "found-footage" },
    { title: "REC", genre: "found-footage" },
    { title: "REC 2", genre: "found-footage" },
    { title: "Creep", genre: "found-footage" },
    { title: "Creep 2", genre: "found-footage" },
    { title: "As Above, So Below", genre: "found-footage" },
    { title: "The Taking of Deborah Logan", genre: "found-footage" },
    { title: "V/H/S", genre: "found-footage" },
    { title: "V/H/S/2", genre: "found-footage" },
    { title: "V/H/S: Viral", genre: "found-footage" },
    { title: "V/H/S/94", genre: "found-footage" },
    { title: "V/H/S/99", genre: "found-footage" },
    { title: "V/H/S/85", genre: "found-footage" },
    { title: "V/H/S/Beyond", genre: "found-footage" },
    { title: "Hell House LLC", genre: "found-footage" },
    { title: "Hell House LLC II: The Abaddon Hotel", genre: "found-footage" },
    { title: "Hell House LLC III: Lake of Fire", genre: "found-footage" },
    { title: "Hell House LLC Origins: The Carmichael Manor", genre: "found-footage" },
    { title: "Grave Encounters", genre: "found-footage" },
    { title: "Grave Encounters 2", genre: "found-footage" },
    { title: "Gonjiam: Haunted Asylum", genre: "found-footage" },
    { title: "Host", genre: "found-footage" },
    { title: "The Borderlands", genre: "found-footage" },
    { title: "The Last Exorcism", genre: "found-footage" },
    { title: "The Last Exorcism Part II", genre: "found-footage" },
    { title: "Cloverfield", genre: "found-footage" },
    { title: "Trollhunter", genre: "found-footage" },
    { title: "Lake Mungo", genre: "found-footage" },
    { title: "Noroi: The Curse", genre: "found-footage" },
    { title: "Butterfly Kisses", genre: "found-footage" },
    { title: "The Houses October Built", genre: "found-footage" },
    { title: "The Houses October Built 2", genre: "found-footage" },
    { title: "Afflicted", genre: "found-footage" },
    { title: "The Visit", genre: "found-footage" },
    { title: "Unfriended", genre: "found-footage" },
    { title: "Unfriended: Dark Web", genre: "found-footage" },
    { title: "Searching", genre: "found-footage" },
    { title: "The Den", genre: "found-footage" },
    { title: "Dashcam", genre: "found-footage" },
    { title: "Deadstream", genre: "found-footage" },
    { title: "Incantation", genre: "found-footage" },
    { title: "Savageland", genre: "found-footage" },
    { title: "The Bay", genre: "found-footage" },
    { title: "Willow Creek", genre: "found-footage" },
    { title: "Exists", genre: "found-footage" },
    { title: "The Sacrament", genre: "found-footage" },
    { title: "Phoenix Forgotten", genre: "found-footage" },
    { title: "The Medium", genre: "found-footage" },
    { title: "The Outwaters", genre: "found-footage" },
    { title: "Skinamarink", genre: "found-footage" },
    { title: "Gags The Clown", genre: "found-footage" },
    { title: "The Tunnel", genre: "found-footage" },
    { title: "Devil's Pass", genre: "found-footage" },
    { title: "The Conspiracy", genre: "found-footage" },
    { title: "The Atticus Institute", genre: "found-footage" },
    { title: "Shaun of the Dead", genre: "comedy" },
    { title: "Tucker & Dale vs. Evil", genre: "comedy" },
    { title: "What We Do in the Shadows", genre: "comedy" },
    { title: "Zombieland", genre: "comedy" },
    { title: "Zombieland: Double Tap", genre: "comedy" },
    { title: "Cabin in the Woods", genre: "comedy" },
    { title: "Fright Night", genre: "comedy" },
    { title: "Fright Night (2011)", genre: "comedy" },
    { title: "Gremlins", genre: "comedy" },
    { title: "Gremlins 2: The New Batch", genre: "comedy" },
    { title: "Beetlejuice", genre: "comedy" },
    { title: "Beetlejuice Beetlejuice", genre: "comedy" },
    { title: "Hocus Pocus", genre: "comedy" },
    { title: "Hocus Pocus 2", genre: "comedy" },
    { title: "Death Becomes Her", genre: "comedy" },
    { title: "Young Frankenstein", genre: "comedy" },
    { title: "Scary Movie", genre: "comedy" },
    { title: "Scary Movie 2", genre: "comedy" },
    { title: "Scary Movie 3", genre: "comedy" },
    { title: "Scary Movie 4", genre: "comedy" },
    { title: "Scary Movie 5", genre: "comedy" },
    { title: "Happy Death Day", genre: "comedy" },
    { title: "Happy Death Day 2U", genre: "comedy" },
    { title: "Freaky", genre: "comedy" },
    { title: "The Final Girls", genre: "comedy" },
    { title: "Ready or Not", genre: "comedy" },
    { title: "Werewolves Within", genre: "comedy" },
    { title: "Jennifer's Body", genre: "comedy" },
    { title: "Lisa Frankenstein", genre: "comedy" },
    { title: "Bodies Bodies Bodies", genre: "comedy" },
    { title: "The Blackening", genre: "comedy" },
    { title: "Totally Killer", genre: "comedy" },
    { title: "Renfield", genre: "comedy" },
    { title: "The Babysitter", genre: "comedy" },
    { title: "The Babysitter: Killer Queen", genre: "comedy" },
    { title: "Vampires vs. the Bronx", genre: "comedy" },
    { title: "Little Monsters", genre: "comedy" },
    { title: "Freaks of Nature", genre: "comedy" },
    { title: "Slither", genre: "comedy" },
    { title: "Eight Legged Freaks", genre: "comedy" },
    { title: "Idle Hands", genre: "comedy" },
    { title: "Housebound", genre: "comedy" },
    { title: "Extra Ordinary", genre: "comedy" },
    { title: "Grabbers", genre: "comedy" },
    { title: "Dead Snow", genre: "comedy" },
    { title: "Dead Snow 2: Red vs. Dead", genre: "comedy" },
    { title: "Boys from County Hell", genre: "comedy" },
    { title: "Knights of Badassdom", genre: "comedy" },
    { title: "The Frighteners", genre: "comedy" },
    { title: "Dark Shadows", genre: "comedy" },
    { title: "The Addams Family", genre: "comedy" },
    { title: "Addams Family Values", genre: "comedy" },
    { title: "Elvira: Mistress of the Dark", genre: "comedy" },
    { title: "Deathgasm", genre: "comedy" },
    { title: "Psycho Goreman", genre: "comedy" },
    { title: "The Wolf of Snow Hollow", genre: "comedy" },
    { title: "Cooties", genre: "comedy" },
    { title: "Fido", genre: "comedy" },
    { title: "The Greasy Strangler", genre: "comedy" },
    { title: "Villains", genre: "comedy" },
    { title: "Satanic Panic", genre: "comedy" },
    { title: "Tragedy Girls", genre: "comedy" },
    { title: "Mom and Dad", genre: "comedy" },
    { title: "Mayhem", genre: "comedy" },
    { title: "Vicious Fun", genre: "comedy" },
    { title: "The Menu", genre: "comedy" },
    { title: "Werewolf by Night", genre: "comedy" },
    { title: "Alien", genre: "sci-fi" },
    { title: "Aliens", genre: "sci-fi" },
    { title: "Alien 3", genre: "sci-fi" },
    { title: "Alien: Resurrection", genre: "sci-fi" },
    { title: "Prometheus", genre: "sci-fi" },
    { title: "Alien: Covenant", genre: "sci-fi" },
    { title: "The Thing", genre: "sci-fi" },
    { title: "The Thing (2011)", genre: "sci-fi" },
    { title: "Event Horizon", genre: "sci-fi" },
    { title: "Pandorum", genre: "sci-fi" },
    { title: "Sunshine", genre: "sci-fi" },
    { title: "Life", genre: "sci-fi" },
    { title: "Annihilation", genre: "sci-fi" },
    { title: "Underwater", genre: "sci-fi" },
    { title: "Sputnik", genre: "sci-fi" },
    { title: "Possessor", genre: "sci-fi" },
    { title: "The Void", genre: "sci-fi" },
    { title: "Color Out of Space", genre: "sci-fi" },
    { title: "Invasion of the Body Snatchers", genre: "sci-fi" },
    { title: "The Faculty", genre: "sci-fi" },
    { title: "Species", genre: "sci-fi" },
    { title: "Species II", genre: "sci-fi" },
    { title: "Species III", genre: "sci-fi" },
    { title: "Species: The Awakening", genre: "sci-fi" },
    { title: "The Fly", genre: "sci-fi" },
    { title: "The Fly II", genre: "sci-fi" },
    { title: "Scanners", genre: "sci-fi" },
    { title: "Videodrome", genre: "sci-fi" },
    { title: "eXistenZ", genre: "sci-fi" },
    { title: "Cube", genre: "sci-fi" },
    { title: "Cube 2: Hypercube", genre: "sci-fi" },
    { title: "Cube Zero", genre: "sci-fi" },
    { title: "Infinity Chamber", genre: "sci-fi" },
    { title: "Upgrade", genre: "sci-fi" },
    { title: "The Endless", genre: "sci-fi" },
    { title: "Resolution", genre: "sci-fi" },
    { title: "The Signal", genre: "sci-fi" },
    { title: "The Fourth Kind", genre: "sci-fi" },
    { title: "Dark Skies", genre: "sci-fi" },
    { title: "Fire in the Sky", genre: "sci-fi" },
    { title: "Nope", genre: "sci-fi" },
    { title: "No One Will Save You", genre: "sci-fi" },
    { title: "10 Cloverfield Lane", genre: "sci-fi" },
    { title: "Cloverfield", genre: "sci-fi" },
    { title: "The Cloverfield Paradox", genre: "sci-fi" },
    { title: "A Quiet Place", genre: "sci-fi" },
    { title: "A Quiet Place Part II", genre: "sci-fi" },
    { title: "A Quiet Place: Day One", genre: "sci-fi" },
    { title: "Bird Box", genre: "sci-fi" },
    { title: "Bird Box Barcelona", genre: "sci-fi" },
    { title: "The Platform", genre: "sci-fi" },
    { title: "The Platform 2", genre: "sci-fi" },
    { title: "Vivarium", genre: "sci-fi" },
    { title: "The Vast of Night", genre: "sci-fi" },
    { title: "The Invisible Man", genre: "sci-fi" },
    { title: "M3GAN", genre: "sci-fi" },
    { title: "M3GAN 2.0", genre: "sci-fi" },
    { title: "The Terminator", genre: "sci-fi" },
    { title: "Terminator 2: Judgment Day", genre: "sci-fi" },
    { title: "Predator", genre: "sci-fi" },
    { title: "Prey", genre: "sci-fi" },
    { title: "The Predator", genre: "sci-fi" },
    { title: "The Host", genre: "sci-fi" },
    { title: "Crimes of the Future", genre: "sci-fi" },
];