const horrorMovies = [
    { title: "The Cabinet of Dr. Caligari", genre: "classic", imdbId: "tt0010323" },
    { title: "Nosferatu", genre: "classic", imdbId: "tt5040012" },
    { title: "Dracula", genre: "classic", imdbId: "tt0103874" },
    { title: "Frankenstein", genre: "classic", imdbId: "tt1312221" },
    { title: "The Mummy", genre: "classic", imdbId: "tt0120616" },
    { title: "The Invisible Man", genre: "classic", imdbId: "tt1051906" },
    { title: "The Wolf Man", genre: "classic", imdbId: "tt0034398" },
    { title: "Creature from the Black Lagoon", genre: "classic", imdbId: "tt0046876" },
    { title: "Cat People", genre: "classic", imdbId: "tt0034587" },
    { title: "I Walked with a Zombie", genre: "classic", imdbId: "tt0036027" },
    { title: "The Body Snatcher", genre: "classic", imdbId: "tt0037549" },
    { title: "House of Wax", genre: "classic", imdbId: "tt0397065" },
    { title: "The Thing from Another World", genre: "classic", imdbId: "tt0044121" },
    { title: "Invasion of the Body Snatchers", genre: "classic", imdbId: "tt0077745" },
    { title: "The Fly", genre: "classic", imdbId: "tt0091064" },
    { title: "The Haunting", genre: "classic", imdbId: "tt0171363" },
    { title: "House on Haunted Hill", genre: "classic", imdbId: "tt0185371" },
    { title: "Psycho", genre: "classic", imdbId: "tt0054215" },
    { title: "The Birds", genre: "classic", imdbId: "tt0056869" },
    { title: "Rosemary's Baby", genre: "classic", imdbId: "tt0063522" },
    { title: "Night of the Living Dead", genre: "classic", imdbId: "tt0063350" },
    { title: "The Wicker Man", genre: "classic", imdbId: "tt0070917" },
    { title: "The Texas Chain Saw Massacre", genre: "classic", imdbId: "tt0072271" },
    { title: "Black Christmas", genre: "classic", imdbId: "tt0071222" },
    { title: "Carrie", genre: "classic", imdbId: "tt0074285" },
    { title: "Suspiria", genre: "classic", imdbId: "tt0076786" },
    { title: "Dawn of the Dead", genre: "classic", imdbId: "tt0363547" },
    { title: "The Omen", genre: "classic", imdbId: "tt0075005" },
    { title: "Jaws", genre: "classic", imdbId: "tt0073195" },
    { title: "Alien", genre: "classic", imdbId: "tt0078748" },
    { title: "Halloween", genre: "classic", imdbId: "tt0077651" },
    { title: "The Shining", genre: "classic", imdbId: "tt0081505" },
    { title: "The Evil Dead", genre: "classic", imdbId: "tt0083907" },
    { title: "A Nightmare on Elm Street", genre: "classic", imdbId: "tt0087800" },
    { title: "The Lost Boys", genre: "classic", imdbId: "tt0093437" },
    { title: "The Fog", genre: "classic", imdbId: "tt0080749" },
    { title: "The Changeling", genre: "classic", imdbId: "tt0080516" },
    { title: "The Amityville Horror", genre: "classic", imdbId: "tt0384806" },
    { title: "The Howling", genre: "classic", imdbId: "tt0082533" },
    { title: "The Return of the Living Dead", genre: "classic", imdbId: "tt0089907" },
    { title: "Child's Play", genre: "classic", imdbId: "tt0094862" },
    { title: "Hellraiser", genre: "classic", imdbId: "tt0093177" },
    { title: "Poltergeist", genre: "classic", imdbId: "tt0084516" },
    { title: "Gremlins", genre: "classic", imdbId: "tt0087363" },
    { title: "The Blob", genre: "classic", imdbId: "tt0094761" },
    { title: "Christine", genre: "classic", imdbId: "tt0085333" },
    { title: "The Exorcist", genre: "classic", imdbId: "tt0070047" },
    { title: "The Exorcist III", genre: "classic", imdbId: "tt0099528" },
    { title: "The Silence of the Lambs", genre: "classic", imdbId: "tt0102926" },
    { title: "Candyman", genre: "classic", imdbId: "tt0103919" },
    { title: "Misery", genre: "classic", imdbId: "tt0100157" },
    { title: "Jacob's Ladder", genre: "classic", imdbId: "tt0099871" },
    { title: "Tremors", genre: "classic", imdbId: "tt0100814" },
    { title: "Army of Darkness", genre: "classic", imdbId: "tt0106308" },
    { title: "Bram Stoker's Dracula", genre: "classic", imdbId: "tt0103874" },
    { title: "Interview with the Vampire", genre: "classic", imdbId: "tt0110148" },
    { title: "Scream", genre: "classic", imdbId: "tt0117571" },
    { title: "The Craft", genre: "classic", imdbId: "tt0115963" },
    { title: "From Dusk Till Dawn", genre: "classic", imdbId: "tt0116367" },
    { title: "Event Horizon", genre: "classic", imdbId: "tt0119081" },
    { title: "The Faculty", genre: "classic", imdbId: "tt0133751" },
    { title: "Sleepy Hollow", genre: "classic", imdbId: "tt0162661" },
    { title: "The Blair Witch Project", genre: "classic", imdbId: "tt0185937" },
    { title: "Friday the 13th", genre: "slasher", imdbId: "tt0080761" },
    { title: "Friday the 13th Part 2", genre: "slasher", imdbId: "tt0082418" },
    { title: "Friday the 13th Part III", genre: "slasher", imdbId: "tt0083972" },
    { title: "Friday the 13th: The Final Chapter", genre: "slasher", imdbId: "tt0087298" },
    { title: "Friday the 13th Part VI: Jason Lives", genre: "slasher", imdbId: "tt0091080" },
    { title: "Friday the 13th Part VII: The New Blood", genre: "slasher", imdbId: "tt0095179" },
    { title: "Friday the 13th Part VIII: Jason Takes Manhattan", genre: "slasher", imdbId: "tt0097388" },
    { title: "Jason Goes to Hell: The Final Friday", genre: "slasher", imdbId: "tt0107254" },
    { title: "Freddy vs. Jason", genre: "slasher", imdbId: "tt0329101" },
     { title: "A Nightmare on Elm Street (1984)", genre: "slasher", imdbId: "tt0087800" },
     { title: "A Nightmare on Elm Street (2010)", genre: "slasher", imdbId: "tt1179056" },
    { title: "A Nightmare on Elm Street 2: Freddy's Revenge", genre: "slasher", imdbId: "tt0089686" },
    { title: "A Nightmare on Elm Street 3: Dream Warriors", genre: "slasher", imdbId: "tt0093629" },
    { title: "A Nightmare on Elm Street 4: The Dream Master", genre: "slasher", imdbId: "tt0095742" },
    { title: "A Nightmare on Elm Street 5: The Dream Child", genre: "slasher", imdbId: "tt0097981" },
    { title: "Wes Craven's New Nightmare", genre: "slasher", imdbId: "tt0111686" },
    { title: "Halloween II", genre: "slasher", imdbId: "tt0082495" },
    { title: "Halloween III: Season of the Witch", genre: "slasher", imdbId: "tt0085636" },
    { title: "Halloween 4: The Return of Michael Myers", genre: "slasher", imdbId: "tt0095271" },
    { title: "Halloween 5: The Revenge of Michael Myers", genre: "slasher", imdbId: "tt0097474" },
    { title: "Halloween H20", genre: "slasher" },
    { title: "Halloween: Resurrection", genre: "slasher", imdbId: "tt0220506" },
    { title: "Halloween (2007)", genre: "slasher" },
    { title: "Halloween II (2009)", genre: "slasher" },
    { title: "Halloween (2018)", genre: "slasher" },
    { title: "Halloween Kills", genre: "slasher", imdbId: "tt10665338" },
    { title: "Halloween Ends", genre: "slasher", imdbId: "tt10665342" },
    { title: "Scream 2", genre: "slasher", imdbId: "tt0120082" },
    { title: "Scream 3", genre: "slasher", imdbId: "tt0134084" },
    { title: "Scream 4", genre: "slasher", imdbId: "tt1262416" },
    { title: "Scream (2022)", genre: "slasher" },
    { title: "Scream VI", genre: "slasher", imdbId: "tt17663992" },
    { title: "I Know What You Did Last Summer", genre: "slasher", imdbId: "tt0119345" },
    { title: "I Still Know What You Did Last Summer", genre: "slasher", imdbId: "tt0130018" },
    { title: "Urban Legend", genre: "slasher", imdbId: "tt0146336" },
    { title: "Urban Legends: Final Cut", genre: "slasher", imdbId: "tt0192731" },
    { title: "Final Destination", genre: "slasher", imdbId: "tt0195714" },
    { title: "Final Destination 2", genre: "slasher", imdbId: "tt0309593" },
    { title: "Final Destination 3", genre: "slasher", imdbId: "tt0414982" },
    { title: "The Final Destination", genre: "slasher", imdbId: "tt1144884" },
    { title: "Final Destination 5", genre: "slasher", imdbId: "tt1622979" },
    { title: "Final Destination: Bloodlines", genre: "slasher", imdbId: "tt9619824" },
    { title: "Texas Chainsaw Massacre (2003)", genre: "slasher" },
    { title: "The Texas Chainsaw Massacre: The Beginning", genre: "slasher", imdbId: "tt0420294" },
    { title: "Hatchet", genre: "slasher", imdbId: "tt0422401" },
    { title: "Hatchet II", genre: "slasher", imdbId: "tt1270835" },
    { title: "Hatchet III", genre: "slasher", imdbId: "tt1870419" },
    { title: "Hatchet IV: Victor Crowley", genre: "slasher" },
    { title: "Terrifier", genre: "slasher", imdbId: "tt4281724" },
    { title: "Terrifier 2", genre: "slasher", imdbId: "tt10403420" },
    { title: "Terrifier 3", genre: "slasher", imdbId: "tt27911000" },
    { title: "Pearl", genre: "slasher", imdbId: "tt18925334" },
    { title: "X", genre: "slasher", imdbId: "tt13560574" },
    { title: "Thanksgiving", genre: "slasher", imdbId: "tt1448754" },
    { title: "Thanksgiving (2023)", genre: "slasher" },
    { title: "Freaky", genre: "slasher", imdbId: "tt10919380" },
    { title: "Fear Street Part One: 1994", genre: "slasher" },
    { title: "Fear Street Part Two: 1978", genre: "slasher" },
    { title: "Fear Street Part Three: 1666", genre: "slasher" },
    { title: "Ready or Not", genre: "slasher", imdbId: "tt7798634" },
    { title: "You're Next", genre: "slasher", imdbId: "tt1853739" },
    { title: "The Strangers", genre: "slasher", imdbId: "tt0482606" },
    { title: "The Strangers: Prey at Night", genre: "slasher", imdbId: "tt1285009" },
    { title: "Black Christmas (2006)", genre: "slasher", imdbId: "tt0454082" },
    { title: "Black Christmas (2019)", genre: "slasher", imdbId: "tt10481868" },
    { title: "Prom Night", genre: "slasher", imdbId: "tt0926129" },
    { title: "My Bloody Valentine", genre: "slasher", imdbId: "tt1179891" },
    { title: "Sleepaway Camp", genre: "slasher", imdbId: "tt0086320" },
    { title: "Maniac", genre: "slasher", imdbId: "tt2103217" },
    { title: "The Prowler", genre: "slasher", imdbId: "tt0082951" },
    { title: "The Burning", genre: "slasher", imdbId: "tt0082118" },
    { title: "The House on Sorority Row", genre: "slasher", imdbId: "tt0085694" },
    { title: "Happy Death Day", genre: "slasher", imdbId: "tt5308322" },
    { title: "Happy Death Day 2U", genre: "slasher", imdbId: "tt8155288" },
    { title: "Behind the Mask: The Rise of Leslie Vernon", genre: "slasher", imdbId: "tt0437857" },
    { title: "Stage Fright", genre: "slasher", imdbId: "tt0042994" },
    { title: "The Collector", genre: "slasher", imdbId: "tt0844479" },
    { title: "The Collection", genre: "slasher", imdbId: "tt1748227" },
    { title: "Hell Fest", genre: "slasher", imdbId: "tt1999890" },
    { title: "The Conjuring", genre: "supernatural", imdbId: "tt1457767" },
    { title: "The Conjuring 2", genre: "supernatural", imdbId: "tt3065204" },
    { title: "The Conjuring: The Devil Made Me Do It", genre: "supernatural", imdbId: "tt7069210" },
    { title: "Annabelle", genre: "supernatural", imdbId: "tt3322940" },
    { title: "Annabelle: Creation", genre: "supernatural", imdbId: "tt5140878" },
    { title: "Annabelle Comes Home", genre: "supernatural", imdbId: "tt8350360" },
    { title: "The Nun", genre: "supernatural", imdbId: "tt5814060" },
    { title: "The Nun II", genre: "supernatural", imdbId: "tt10160976" },
    { title: "Insidious", genre: "supernatural", imdbId: "tt1591095" },
    { title: "Insidious: Chapter 2", genre: "supernatural", imdbId: "tt2226417" },
    { title: "Insidious: Chapter 3", genre: "supernatural", imdbId: "tt3195644" },
    { title: "Insidious: The Last Key", genre: "supernatural", imdbId: "tt5726086" },
    { title: "Insidious: The Red Door", genre: "supernatural", imdbId: "tt13405778" },
    { title: "Sinister", genre: "supernatural", imdbId: "tt1922777" },
    { title: "Sinister 2", genre: "supernatural", imdbId: "tt2752772" },
    { title: "The Ring", genre: "supernatural", imdbId: "tt0298130" },
    { title: "The Ring Two", genre: "supernatural", imdbId: "tt0377109" },
    { title: "Ringu", genre: "supernatural", imdbId: "tt0178868" },
    { title: "The Grudge", genre: "supernatural", imdbId: "tt0391198" },
    { title: "The Grudge 2", genre: "supernatural", imdbId: "tt0433386" },
    { title: "Ju-On: The Grudge", genre: "supernatural", imdbId: "tt0364385" },
    { title: "It", genre: "supernatural", imdbId: "tt1396484" },
    { title: "It Chapter Two", genre: "supernatural", imdbId: "tt7349950" },
    { title: "The Others", genre: "supernatural", imdbId: "tt0230600" },
    { title: "The Sixth Sense", genre: "supernatural", imdbId: "tt0167404" },
    { title: "The Woman in Black", genre: "supernatural", imdbId: "tt1596365" },
    { title: "The Woman in Black 2: Angel of Death", genre: "supernatural", imdbId: "tt2339741" },
    { title: "Oculus", genre: "supernatural", imdbId: "tt2388715" },
    { title: "Ouija", genre: "supernatural", imdbId: "tt1204977" },
    { title: "Ouija: Origin of Evil", genre: "supernatural", imdbId: "tt4361050" },
    { title: "Lights Out", genre: "supernatural", imdbId: "tt4786282" },
    { title: "The Autopsy of Jane Doe", genre: "supernatural", imdbId: "tt3289956" },
    { title: "The Exorcism of Emily Rose", genre: "supernatural", imdbId: "tt0404032" },
    { title: "The Taking of Deborah Logan", genre: "supernatural", imdbId: "tt3387648" },
    { title: "The Possession", genre: "supernatural", imdbId: "tt0431021" },
    { title: "The Possession of Michael King", genre: "supernatural", imdbId: "tt2282016" },
    { title: "The Dark and the Wicked", genre: "supernatural", imdbId: "tt10229558" },
    { title: "The Vigil", genre: "supernatural", imdbId: "tt10793644" },
    { title: "The Empty Man", genre: "supernatural", imdbId: "tt5867314" },
    { title: "Smile", genre: "supernatural", imdbId: "tt15474916" },
    { title: "Smile 2", genre: "supernatural", imdbId: "tt29268110" },
    { title: "Talk to Me", genre: "supernatural", imdbId: "tt10638522" },
    { title: "The Black Phone", genre: "supernatural", imdbId: "tt7144666" },
    { title: "The Boogeyman", genre: "supernatural", imdbId: "tt3427252" },
    { title: "Evil Dead Rise", genre: "supernatural", imdbId: "tt13345606" },
    { title: "Drag Me to Hell", genre: "supernatural", imdbId: "tt1127180" },
    { title: "Dead Silence", genre: "supernatural", imdbId: "tt0455760" },
    { title: "1408", genre: "supernatural", imdbId: "tt0450385" },
    { title: "The Skeleton Key", genre: "supernatural", imdbId: "tt0397101" },
    { title: "The Devil's Backbone", genre: "supernatural", imdbId: "tt0256009" },
    { title: "The Orphanage", genre: "supernatural", imdbId: "tt0464141" },
    { title: "The Innocents", genre: "supernatural", imdbId: "tt0055018" },
    { title: "His House", genre: "supernatural", imdbId: "tt8508734" },
    { title: "Host", genre: "supernatural", imdbId: "tt12749596" },
    { title: "The Night House", genre: "supernatural", imdbId: "tt9731534" },
    { title: "The Lodge", genre: "supernatural", imdbId: "tt7347846" },
    { title: "The Ritual", genre: "supernatural", imdbId: "tt5638642" },
    { title: "The Medium", genre: "supernatural", imdbId: "tt13446168" },
    { title: "Veronica", genre: "supernatural", imdbId: "tt5862312" },
    { title: "The Wailing", genre: "supernatural", imdbId: "tt5215952" },
    { title: "Incantation", genre: "supernatural", imdbId: "tt18968540" },
    { title: "The Pope's Exorcist", genre: "supernatural", imdbId: "tt13375076" },
    { title: "Late Night with the Devil", genre: "supernatural", imdbId: "tt14966898" },
    { title: "The First Omen", genre: "supernatural", imdbId: "tt5672290" },
    { title: "Abigail", genre: "supernatural", imdbId: "tt27489557" },
    { title: "The Watchers", genre: "supernatural", imdbId: "tt26736843" },
    { title: "Oddity", genre: "supernatural", imdbId: "tt26470109" },
    { title: "Longlegs", genre: "supernatural", imdbId: "tt23468450" },
    { title: "Get Out", genre: "psychological", imdbId: "tt5052448" },
    { title: "Us", genre: "psychological", imdbId: "tt6857112" },
    { title: "Nope", genre: "psychological", imdbId: "tt10954984" },
    { title: "The Witch", genre: "psychological", imdbId: "tt4263482" },
    { title: "Hereditary", genre: "psychological", imdbId: "tt7784604" },
    { title: "Midsommar", genre: "psychological", imdbId: "tt8772262" },
    { title: "The Lighthouse", genre: "psychological", imdbId: "tt7984734" },
    { title: "Black Swan", genre: "psychological", imdbId: "tt0947798" },
    { title: "The Invitation", genre: "psychological", imdbId: "tt2400463" },
    { title: "Enemy", genre: "psychological", imdbId: "tt2316411" },
    { title: "Shutter Island", genre: "psychological", imdbId: "tt1130884" },
    { title: "The Machinist", genre: "psychological", imdbId: "tt0361862" },
    { title: "American Psycho", genre: "psychological", imdbId: "tt0144084" },
    { title: "The Killing of a Sacred Deer", genre: "psychological", imdbId: "tt5715874" },
    { title: "The Babadook", genre: "psychological", imdbId: "tt2321549" },
    { title: "Saint Maud", genre: "psychological", imdbId: "tt7557108" },
    { title: "The Lodge", genre: "psychological", imdbId: "tt7347846" },
    { title: "The Perfection", genre: "psychological", imdbId: "tt7772580" },
    { title: "Cam", genre: "psychological", imdbId: "tt8361028" },
    { title: "Creep", genre: "psychological", imdbId: "tt2428170" },
    { title: "Creep 2", genre: "psychological", imdbId: "tt3654796" },
    { title: "The Platform", genre: "psychological", imdbId: "tt8228288" },
    { title: "The Invisible Man (2020)", genre: "psychological" },
    { title: "Barbarian", genre: "psychological", imdbId: "tt15791034" },
    { title: "Fresh", genre: "psychological", imdbId: "tt13403046" },
    { title: "Watcher", genre: "psychological", imdbId: "tt12004038" },
    { title: "Speak No Evil", genre: "psychological", imdbId: "tt27534307" },
    { title: "The Menu", genre: "psychological", imdbId: "tt9764362" },
    { title: "Infinity Pool", genre: "psychological", imdbId: "tt10365998" },
    { title: "Possessor", genre: "psychological", imdbId: "tt5918982" },
    { title: "The Skin I Live In", genre: "psychological", imdbId: "tt1189073" },
    { title: "Funny Games", genre: "psychological", imdbId: "tt0808279" },
    { title: "The House That Jack Built", genre: "psychological", imdbId: "tt4003440" },
    { title: "Mother!", genre: "psychological", imdbId: "tt5109784" },
    { title: "Climax", genre: "psychological", imdbId: "tt8359848" },
    { title: "Raw", genre: "psychological", imdbId: "tt4954522" },
    { title: "Titane", genre: "psychological", imdbId: "tt10944760" },
    { title: "Swallow", genre: "psychological", imdbId: "tt8372298" },
    { title: "The Neon Demon", genre: "psychological", imdbId: "tt1974419" },
    { title: "Perfect Blue", genre: "psychological", imdbId: "tt0156887" },
    { title: "Audition", genre: "psychological", imdbId: "tt0235198" },
    { title: "Oldboy", genre: "psychological", imdbId: "tt0364569" },
    { title: "Session 9", genre: "psychological", imdbId: "tt0261983" },
    { title: "Frailty", genre: "psychological", imdbId: "tt0264616" },
    { title: "Identity", genre: "psychological", imdbId: "tt0309698" },
    { title: "1408", genre: "psychological", imdbId: "tt0450385" },
    { title: "Secret Window", genre: "psychological", imdbId: "tt0363988" },
    { title: "Cape Fear", genre: "psychological", imdbId: "tt0101540" },
    { title: "The Game", genre: "psychological", imdbId: "tt0119174" },
    { title: "Primal Fear", genre: "psychological", imdbId: "tt0117381" },
    { title: "Se7en", genre: "psychological", imdbId: "tt0114369" },
    { title: "Zodiac", genre: "psychological", imdbId: "tt0443706" },
    { title: "The Silence of the Lambs", genre: "psychological", imdbId: "tt0102926" },
    { title: "The Vanishing", genre: "psychological", imdbId: "tt0096163" },
    { title: "We Need to Talk About Kevin", genre: "psychological", imdbId: "tt1242460" },
    { title: "Vivarium", genre: "psychological", imdbId: "tt8368406" },
    { title: "The One I Love", genre: "psychological", imdbId: "tt2756032" },
    { title: "Coherence", genre: "psychological", imdbId: "tt2866360" },
    { title: "Triangle", genre: "psychological", imdbId: "tt1187064" },
    { title: "The Invitation (2015)", genre: "psychological", imdbId:"tt12873562" },
    { title: "Calibre", genre: "psychological", imdbId: "tt6218358" },
    { title: "The Platform 2", genre: "psychological", imdbId: "tt27729779" },
    { title: "Nocturnal Animals", genre: "psychological", imdbId: "tt4550098" },
    { title: "The Gift", genre: "psychological", imdbId: "tt4178092" },
    { title: "Unsane", genre: "psychological", imdbId: "tt7153766" },
    { title: "Run", genre: "psychological", imdbId: "tt8633478" },
    { title: "Watcher (2022)", genre: "psychological", imdbId: "tt12004038" },
    { title: "Goodnight Mommy", genre: "psychological", imdbId: "tt3086442" },
    { title: "The Night House", genre: "psychological", imdbId: "tt9731534" },
    { title: "Relic", genre: "psychological", imdbId: "tt9072352" },
    { title: "Resurrection", genre: "psychological", imdbId: "tt7738784" },
    { title: "Predator", genre: "creature", imdbId: "tt0093773" },
    { title: "Predator 2", genre: "creature", imdbId: "tt0100403" },
    { title: "Prey", genre: "creature", imdbId: "tt11866324" },
    { title: "Cloverfield", genre: "creature", imdbId: "tt1060277" },
    { title: "10 Cloverfield Lane", genre: "creature", imdbId: "tt1179933" },
    { title: "The Mist", genre: "creature", imdbId: "tt0884328" },
    { title: "An American Werewolf in London", genre: "creature", imdbId: "tt0082010" },
    { title: "Dog Soldiers", genre: "creature", imdbId: "tt0280609" },
    { title: "The Descent", genre: "creature", imdbId: "tt0435625" },
    { title: "The Descent Part 2", genre: "creature", imdbId: "tt1073105" },
    { title: "The Host", genre: "creature", imdbId: "tt0468492" },
    { title: "Underwater", genre: "creature", imdbId: "tt5774060" },
    { title: "Deep Rising", genre: "creature", imdbId: "tt0118956" },
    { title: "Leviathan", genre: "creature", imdbId: "tt2802154" },
    { title: "Sphere", genre: "creature", imdbId: "tt0120184" },
    { title: "Mimic", genre: "creature", imdbId: "tt0119675" },
    { title: "Mimic 2", genre: "creature", imdbId: "tt0239641" },
    { title: "Mimic 3: Sentinel", genre: "creature", imdbId: "tt0330634" },
    { title: "The Relic", genre: "creature", imdbId: "tt0120004" },
    { title: "Slither", genre: "creature", imdbId: "tt0439815" },
    { title: "Splinter", genre: "creature", imdbId: "tt1031280" },
    { title: "The Void", genre: "creature", imdbId: "tt4255304" },
    { title: "The Ritual", genre: "creature", imdbId: "tt5638642" },
    { title: "The Ruins", genre: "creature", imdbId: "tt0963794" },
    { title: "The Cave", genre: "creature", imdbId: "tt0402901" },
    { title: "Sweetheart", genre: "creature", imdbId: "tt6560164" },
    { title: "Sea Fever", genre: "creature", imdbId: "tt2716382" },
    { title: "Sputnik", genre: "creature", imdbId: "tt11905962" },
    { title: "Life", genre: "creature", imdbId: "tt5442430" },
    { title: "The Cloverfield Paradox", genre: "creature", imdbId: "tt2548396" },
    { title: "No One Will Save You", genre: "creature", imdbId: "tt14509110" },
    { title: "The Faculty", genre: "creature", imdbId: "tt0133751" },
    { title: "The Blob (1988)", genre: "creature", imdbId:"tt0094761" },
    { title: "Pumpkinhead", genre: "creature", imdbId: "tt0095925" },
    { title: "Pumpkinhead II", genre: "creature", imdbId: "tt40902212" },
    { title: "Jeepers Creepers", genre: "creature", imdbId: "tt0263488" },
    { title: "Jeepers Creepers 2", genre: "creature", imdbId: "tt0301470" },
    { title: "Jeepers Creepers 3", genre: "creature", imdbId: "tt1139592" },
    { title: "Jeepers Creepers: Reborn", genre: "creature", imdbId: "tt14121726" },
    { title: "The Monster", genre: "creature", imdbId: "tt3976144" },
    { title: "The Host (2006)", genre: "creature", imdbId:"tt0468492" },
    { title: "The Shape of Water", genre: "creature", imdbId: "tt5580390" },
    { title: "The Lair", genre: "creature", imdbId: "tt13468602" },
    { title: "Black Mountain Side", genre: "creature", imdbId: "tt3139756" },
    { title: "Cold Skin", genre: "creature", imdbId: "tt1034385" },
    { title: "The Hallow", genre: "creature", imdbId: "tt2474976" },
    { title: "The Monster Project", genre: "creature", imdbId: "tt4537888" },
    { title: "The Boogeyman", genre: "creature", imdbId: "tt3427252" },
    { title: "Antlers", genre: "creature", imdbId: "tt7740510" },
    { title: "The Wolfman", genre: "creature", imdbId: "tt0780653" },
    { title: "Werewolves Within", genre: "creature", imdbId: "tt9288692" },
    { title: "Ginger Snaps", genre: "creature", imdbId: "tt0210070" },
    { title: "Ginger Snaps 2", genre: "creature", imdbId: "tt0210070" },
    { title: "Ginger Snaps Back", genre: "creature", imdbId:"tt0365265" },
    { title: "Late Phases", genre: "creature", imdbId: "tt2420756" },
    { title: "The Cursed", genre: "creature", imdbId: "tt9907782" },
    { title: "When Animals Dream", genre: "creature", imdbId: "tt2818178" },
    { title: "The Company of Wolves", genre: "creature", imdbId: "tt0087075" },
    { title: "The Howling", genre: "creature", imdbId: "tt0082533" },
    { title: "28 Days Later", genre: "zombie", imdbId: "tt0289043" },
    { title: "28 Weeks Later", genre: "zombie", imdbId: "tt0463854" },
    { title: "28 Years Later", genre: "zombie", imdbId: "tt10548174" },
    { title: "Train to Busan", genre: "zombie", imdbId: "tt5700672" },
    { title: "Peninsula", genre: "zombie", imdbId: "tt8850222" },
    { title: "World War Z", genre: "zombie", imdbId: "tt0816711" },
    { title: "Shaun of the Dead", genre: "zombie", imdbId: "tt0365748" },
    { title: "Dawn of the Dead", genre: "zombie", imdbId: "tt0363547" },
    { title: "Day of the Dead", genre: "zombie", imdbId: "tt0088993" },
    { title: "Land of the Dead", genre: "zombie", imdbId: "tt0418819" },
    { title: "Diary of the Dead", genre: "zombie", imdbId: "tt0848557" },
    { title: "Survival of the Dead", genre: "zombie", imdbId: "tt1134854" },
    { title: "Army of the Dead", genre: "zombie", imdbId: "tt0993840" },
    { title: "Zombieland", genre: "zombie", imdbId: "tt1156398" },
    { title: "Zombieland: Double Tap", genre: "zombie", imdbId: "tt1560220" },
    { title: "Warm Bodies", genre: "zombie", imdbId: "tt1588173" },
    { title: "Rec", genre: "zombie", imdbId: "tt1038988" },
    { title: "[REC] 2", genre: "zombie", imdbId:"tt1245112" },
    { title: "[REC] 3: Genesis", genre: "zombie", imdbId: "tt1649444" },
    { title: "[REC] 4: Apocalypse", genre: "zombie", imdbId: "tt1649443" },
    { title: "The Girl with All the Gifts", genre: "zombie", imdbId: "tt4547056" },
    { title: "The Cured", genre: "zombie", imdbId: "tt3463106" },
    { title: "The Battery", genre: "zombie", imdbId: "tt2272350" },
    { title: "Pontypool", genre: "zombie", imdbId: "tt1226681" },
    { title: "Ravenous", genre: "zombie", imdbId: "tt0129332" },
    { title: "The Night Eats the World", genre: "zombie", imdbId: "tt4266076" },
    { title: "One Cut of the Dead", genre: "zombie", imdbId: "tt7914416" },
    { title: "Little Monsters", genre: "zombie", imdbId: "tt7390588" },
    { title: "Overlord", genre: "zombie", imdbId: "tt4530422" },
    { title: "Cargo", genre: "zombie", imdbId: "tt3860916" },
    { title: "The Dead Don't Die", genre: "zombie", imdbId: "tt8695030" },
    { title: "Fido", genre: "zombie", imdbId: "tt0457572" },
    { title: "Planet Terror", genre: "zombie", imdbId: "tt1077258" },
    { title: "Resident Evil", genre: "zombie", imdbId: "tt0120804" },
    { title: "Resident Evil: Apocalypse", genre: "zombie", imdbId: "tt0318627" },
    { title: "Resident Evil: Extinction", genre: "zombie", imdbId: "tt0432021" },
    { title: "Resident Evil: Afterlife", genre: "zombie", imdbId: "tt1220634" },
    { title: "Resident Evil: Retribution", genre: "zombie", imdbId: "tt1855325" },
    { title: "Resident Evil: The Final Chapter", genre: "zombie", imdbId: "tt2592614" },
    { title: "Resident Evil: Welcome to Raccoon City", genre: "zombie", imdbId: "tt6920084" },
    { title: "The Sadness", genre: "zombie", imdbId: "tt13872248" },
    { title: "The Horde", genre: "zombie", imdbId: "tt1183276" },
    { title: "The Returned", genre: "zombie", imdbId: "tt2093270" },
    { title: "The Last Days", genre: "zombie", imdbId: "tt1935914" },
    { title: "Maggie", genre: "zombie", imdbId: "tt1881002" },
    { title: "Wyrmwood: Road of the Dead", genre: "zombie", imdbId: "tt2535470" },
    { title: "Wyrmwood: Apocalypse", genre: "zombie", imdbId: "tt14858054" },
    { title: "Dead Snow", genre: "zombie", imdbId: "tt1278340" },
    { title: "Dead Snow 2: Red vs. Dead", genre: "zombie", imdbId: "tt2832470" },
    { title: "Juan of the Dead", genre: "zombie", imdbId: "tt1838571" },
    { title: "Scouts Guide to the Zombie Apocalypse", genre: "zombie", imdbId: "tt1727776" },
    { title: "The Rezort", genre: "zombie", imdbId: "tt3923662" },
    { title: "The Stalled", genre: "zombie", imdbId:"tt2140429" },
    { title: "Blood Quantum", genre: "zombie", imdbId: "tt7394674" },
    { title: "Handling the Undead", genre: "zombie", imdbId: "tt2118648" },
    { title: "Apocalypse Z: The Beginning of the End", genre: "zombie", imdbId: "tt27599851" },
    { title: "The Blair Witch Project", genre: "found-footage", imdbId: "tt0185937" },
    { title: "Paranormal Activity", genre: "found-footage", imdbId: "tt1179904" },
    { title: "Paranormal Activity 2", genre: "found-footage", imdbId: "tt1536044" },
    { title: "Paranormal Activity 3", genre: "found-footage", imdbId: "tt1778304" },
    { title: "Paranormal Activity 4", genre: "found-footage", imdbId: "tt2109184" },
    { title: "Paranormal Activity: The Marked Ones", genre: "found-footage", imdbId: "tt2473682" },
    { title: "Paranormal Activity: The Ghost Dimension", genre: "found-footage", imdbId: "tt2473510" },
    { title: "Paranormal Activity: Next of Kin", genre: "found-footage", imdbId: "tt10515988" },
    { title: "Creep", genre: "found-footage", imdbId: "tt2428170" },
    { title: "Creep 2", genre: "found-footage", imdbId: "tt3654796" },
    { title: "As Above, So Below", genre: "found-footage", imdbId: "tt2870612" },
    { title: "The Taking of Deborah Logan", genre: "found-footage", imdbId: "tt3387648" },
    { title: "V/H/S", genre: "found-footage", imdbId: "tt2105044" },
    { title: "V/H/S/2", genre: "found-footage", imdbId: "tt2450186" },
    { title: "V/H/S: Viral", genre: "found-footage", imdbId: "tt3704538" },
    { title: "V/H/S/94", genre: "found-footage", imdbId: "tt14867006" },
    { title: "V/H/S/99", genre: "found-footage", imdbId: "tt21651560" },
    { title: "V/H/S/85", genre: "found-footage", imdbId: "tt22640398" },
    { title: "V/H/S/Beyond", genre: "found-footage", imdbId: "tt32880932" },
    { title: "Hell House LLC", genre: "found-footage", imdbId: "tt4267026" },
    { title: "Hell House LLC II: The Abaddon Hotel", genre: "found-footage", imdbId: "tt8707374" },
    { title: "Hell House LLC III: Lake of Fire", genre: "found-footage", imdbId: "tt10675136" },
    { title: "Hell House LLC Origins: The Carmichael Manor", genre: "found-footage", imdbId: "tt22796890" },
    { title: "Grave Encounters", genre: "found-footage", imdbId: "tt1703199" },
    { title: "Grave Encounters 2", genre: "found-footage", imdbId: "tt2231554" },
    { title: "Gonjiam: Haunted Asylum", genre: "found-footage", imdbId: "tt8119752" },
    { title: "Host", genre: "found-footage", imdbId: "tt12749596" },
    { title: "The Borderlands", genre: "found-footage", imdbId: "tt2781832" },
    { title: "The Last Exorcism", genre: "found-footage", imdbId: "tt1320244" },
    { title: "The Last Exorcism Part II", genre: "found-footage", imdbId: "tt2034139" },
    { title: "Cloverfield", genre: "found-footage", imdbId: "tt1060277" },
    { title: "Trollhunter", genre: "found-footage", imdbId: "tt1740707" },
    { title: "Lake Mungo", genre: "found-footage", imdbId: "tt0816556" },
    { title: "Noroi: The Curse", genre: "found-footage", imdbId: "tt0930083" },
    { title: "Butterfly Kisses", genre: "found-footage", imdbId: "tt5792468" },
    { title: "The Houses October Built", genre: "found-footage", imdbId: "tt1958043" },
    { title: "The Houses October Built 2", genre: "found-footage", imdbId: "tt7068818" },
    { title: "Afflicted", genre: "found-footage", imdbId: "tt2309961" },
    { title: "The Visit", genre: "found-footage", imdbId: "tt3567288" },
    { title: "Unfriended", genre: "found-footage", imdbId: "tt3713166" },
    { title: "Unfriended: Dark Web", genre: "found-footage", imdbId: "tt4761916" },
    { title: "Searching", genre: "found-footage", imdbId: "tt7668870" },
    { title: "The Den", genre: "found-footage", imdbId: "tt2503154" },
    { title: "Dashcam", genre: "found-footage", imdbId: "tt15174116" },
    { title: "Deadstream", genre: "found-footage", imdbId: "tt12788488" },
    { title: "Incantation", genre: "found-footage", imdbId: "tt18968540" },
    { title: "Savageland", genre: "found-footage", imdbId: "tt3899154" },
    { title: "The Bay", genre: "found-footage", imdbId: "tt1713476" },
    { title: "Willow Creek", genre: "found-footage", imdbId: "tt2885364" },
    { title: "Exists", genre: "found-footage", imdbId: "tt1988621" },
    { title: "The Sacrament", genre: "found-footage", imdbId: "tt2383068" },
    { title: "Phoenix Forgotten", genre: "found-footage", imdbId: "tt6574272" },
    { title: "The Medium", genre: "found-footage", imdbId: "tt13446168" },
    { title: "The Outwaters", genre: "found-footage", imdbId: "tt13259610" },
    { title: "Skinamarink", genre: "found-footage", imdbId: "tt21307994" },
    { title: "Gags The Clown", genre: "found-footage", imdbId: "tt6570372" },
    { title: "The Tunnel", genre: "found-footage", imdbId: "tt1735485" },
    { title: "Devil's Pass", genre: "found-footage", imdbId: "tt1905040" },
    { title: "The Conspiracy", genre: "found-footage", imdbId: "tt2330322" },
    { title: "The Atticus Institute", genre: "found-footage", imdbId: "tt3280916" },
    { title: "Shaun of the Dead", genre: "comedy", imdbId: "tt0365748" },
    { title: "Tucker & Dale vs. Evil", genre: "comedy", imdbId: "tt1465522" },
    { title: "What We Do in the Shadows", genre: "comedy", imdbId: "tt3416742" },
    { title: "Zombieland", genre: "comedy", imdbId: "tt1156398" },
    { title: "Zombieland: Double Tap", genre: "comedy", imdbId: "tt1560220" },
    { title: "Cabin in the Woods", genre: "comedy", imdbId: "tt1259521" },
    { title: "Fright Night", genre: "comedy", imdbId: "tt1438176" },
    { title: "Gremlins", genre: "comedy", imdbId: "tt0087363" },
    { title: "Gremlins 2: The New Batch", genre: "comedy", imdbId: "tt0099700" },
    { title: "Beetlejuice", genre: "comedy", imdbId: "tt0094721" },
    { title: "Beetlejuice Beetlejuice", genre: "comedy", imdbId: "tt2049403" },
    { title: "Hocus Pocus", genre: "comedy", imdbId: "tt0107120" },
    { title: "Hocus Pocus 2", genre: "comedy", imdbId: "tt11909878" },
    { title: "Death Becomes Her", genre: "comedy", imdbId: "tt0104070" },
    { title: "Young Frankenstein", genre: "comedy", imdbId: "tt0072431" },
    { title: "Scary Movie", genre: "comedy", imdbId: "tt0175142" },
    { title: "Scary Movie 2", genre: "comedy", imdbId: "tt0257106" },
    { title: "Scary Movie 3", genre: "comedy", imdbId: "tt0306047" },
    { title: "Scary Movie 4", genre: "comedy", imdbId: "tt0362120" },
    { title: "Scary Movie 5", genre: "comedy", imdbId: "tt0795461" },
    { title: "Happy Death Day", genre: "comedy", imdbId: "tt5308322" },
    { title: "Happy Death Day 2U", genre: "comedy", imdbId: "tt8155288" },
    { title: "Freaky", genre: "comedy", imdbId: "tt10919380" },
    { title: "The Final Girls", genre: "comedy", imdbId: "tt2118624" },
    { title: "Ready or Not", genre: "comedy", imdbId: "tt7798634" },
    { title: "Werewolves Within", genre: "comedy", imdbId: "tt9288692" },
    { title: "Jennifer's Body", genre: "comedy", imdbId: "tt1131734" },
    { title: "Lisa Frankenstein", genre: "comedy", imdbId: "tt21188080" },
    { title: "Bodies Bodies Bodies", genre: "comedy", imdbId: "tt8110652" },
    { title: "The Blackening", genre: "comedy", imdbId: "tt11703244" },
    { title: "Totally Killer", genre: "comedy", imdbId: "tt11426232" },
    { title: "Renfield", genre: "comedy", imdbId: "tt11358390" },
    { title: "The Babysitter", genre: "comedy", imdbId: "tt4225622" },
    { title: "The Babysitter: Killer Queen", genre: "comedy", imdbId: "tt11024272" },
    { title: "Vampires vs. the Bronx", genre: "comedy", imdbId: "tt8976576" },
    { title: "Little Monsters", genre: "comedy", imdbId: "tt7390588" },
    { title: "Freaks of Nature", genre: "comedy", imdbId: "tt1817771" },
    { title: "Slither", genre: "comedy", imdbId: "tt0439815" },
    { title: "Eight Legged Freaks", genre: "comedy", imdbId: "tt0271367" },
    { title: "Idle Hands", genre: "comedy", imdbId: "tt0138510" },
    { title: "Housebound", genre: "comedy", imdbId: "tt3504048" },
    { title: "Extra Ordinary", genre: "comedy", imdbId: "tt8233874" },
    { title: "Grabbers", genre: "comedy", imdbId: "tt1525366" },
    { title: "Dead Snow", genre: "comedy", imdbId: "tt1278340" },
    { title: "Dead Snow 2: Red vs. Dead", genre: "comedy", imdbId: "tt2832470" },
    { title: "Boys from County Hell", genre: "comedy", imdbId: "tt10262380" },
    { title: "Knights of Badassdom", genre: "comedy", imdbId: "tt1545660" },
    { title: "The Frighteners", genre: "comedy", imdbId: "tt0116365" },
    { title: "Dark Shadows", genre: "comedy", imdbId: "tt1077368" },
    { title: "The Addams Family", genre: "comedy", imdbId: "tt0101272" },
    { title: "Addams Family Values", genre: "comedy", imdbId: "tt0106220" },
    { title: "Elvira: Mistress of the Dark", genre: "comedy", imdbId: "tt0095088" },
    { title: "Deathgasm", genre: "comedy", imdbId: "tt3705412" },
    { title: "Psycho Goreman", genre: "comedy", imdbId: "tt11252440" },
    { title: "The Wolf of Snow Hollow", genre: "comedy", imdbId: "tt11140488" },
    { title: "Cooties", genre: "comedy", imdbId: "tt2490326" },
    { title: "Fido", genre: "comedy", imdbId: "tt0457572" },
    { title: "The Greasy Strangler", genre: "comedy", imdbId: "tt4381236" },
    { title: "Villains", genre: "comedy", imdbId: "tt6378710" },
    { title: "Satanic Panic", genre: "comedy", imdbId: "tt8510350" },
    { title: "Tragedy Girls", genre: "comedy", imdbId: "tt3859272" },
    { title: "Mom and Dad", genre: "comedy", imdbId: "tt5462326" },
    { title: "Mayhem", genre: "comedy", imdbId: "tt4348012" },
    { title: "Vicious Fun", genre: "comedy", imdbId: "tt11778118" },
    { title: "The Menu", genre: "comedy", imdbId: "tt9764362" },
    { title: "Werewolf by Night", genre: "comedy" },
    { title: "Alien", genre: "sci-fi", imdbId: "tt0078748" },
    { title: "Aliens", genre: "sci-fi", imdbId: "tt0090605" },
    { title: "Alien 3", genre: "sci-fi" },
    { title: "Alien: Resurrection", genre: "sci-fi", imdbId: "tt0118583" },
    { title: "Prometheus", genre: "sci-fi", imdbId: "tt1446714" },
    { title: "Alien: Covenant", genre: "sci-fi", imdbId: "tt2316204" },
    { title: "The Thing", genre: "sci-fi", imdbId: "tt0084787" },
    { title: "Event Horizon", genre: "sci-fi", imdbId: "tt0119081" },
    { title: "Pandorum", genre: "sci-fi", imdbId: "tt1188729" },
    { title: "Sunshine", genre: "sci-fi", imdbId: "tt0448134" },
    { title: "Life", genre: "sci-fi", imdbId: "tt5442430" },
    { title: "Annihilation", genre: "sci-fi", imdbId: "tt2798920" },
    { title: "Underwater", genre: "sci-fi", imdbId: "tt5774060" },
    { title: "Sputnik", genre: "sci-fi", imdbId: "tt11905962" },
    { title: "Possessor", genre: "sci-fi", imdbId: "tt5918982" },
    { title: "The Void", genre: "sci-fi", imdbId: "tt4255304" },
    { title: "Color Out of Space", genre: "sci-fi", imdbId: "tt5073642" },
    { title: "Invasion of the Body Snatchers", genre: "sci-fi", imdbId: "tt0077745" },
    { title: "The Faculty", genre: "sci-fi", imdbId: "tt0133751" },
    { title: "Species", genre: "sci-fi", imdbId: "tt0114508" },
    { title: "Species II", genre: "sci-fi", imdbId: "tt0120841" },
    { title: "Species III", genre: "sci-fi", imdbId: "tt0120841" },
    { title: "Species: The Awakening", genre: "sci-fi" },
    { title: "The Fly", genre: "sci-fi", imdbId: "tt0091064" },
    { title: "The Fly II", genre: "sci-fi", imdbId: "tt0097368" },
    { title: "Scanners", genre: "sci-fi", imdbId: "tt0081455" },
    { title: "Videodrome", genre: "sci-fi", imdbId: "tt0086541" },
    { title: "eXistenZ", genre: "sci-fi", imdbId: "tt0120907" },
    { title: "Cube", genre: "sci-fi", imdbId: "tt0123755" },
    { title: "Cube 2: Hypercube", genre: "sci-fi", imdbId: "tt0285492" },
    { title: "Cube Zero", genre: "sci-fi", imdbId: "tt0377713" },
    { title: "Infinity Chamber", genre: "sci-fi", imdbId: "tt3839880" },
    { title: "Upgrade", genre: "sci-fi", imdbId: "tt6499752" },
    { title: "The Endless", genre: "sci-fi", imdbId: "tt3986820" },
    { title: "Resolution", genre: "sci-fi", imdbId: "tt1977895" },
    { title: "The Signal", genre: "sci-fi", imdbId: "tt2910814" },
    { title: "The Fourth Kind", genre: "sci-fi", imdbId: "tt1220198" },
    { title: "Dark Skies", genre: "sci-fi", imdbId: "tt2387433" },
    { title: "Fire in the Sky", genre: "sci-fi", imdbId: "tt0106912" },
    { title: "Nope", genre: "sci-fi", imdbId: "tt10954984" },
    { title: "No One Will Save You", genre: "sci-fi", imdbId: "tt14509110" },
    { title: "10 Cloverfield Lane", genre: "sci-fi", imdbId: "tt1179933" },
    { title: "Cloverfield", genre: "sci-fi", imdbId: "tt1060277" },
    { title: "The Cloverfield Paradox", genre: "sci-fi", imdbId: "tt2548396" },
    { title: "A Quiet Place", genre: "sci-fi", imdbId: "tt6644200" },
    { title: "A Quiet Place Part II", genre: "sci-fi", imdbId: "tt8332922" },
    { title: "A Quiet Place: Day One", genre: "sci-fi", imdbId: "tt13433802" },
    { title: "Bird Box", genre: "sci-fi", imdbId: "tt2737304" },
    { title: "Bird Box Barcelona", genre: "sci-fi", imdbId: "tt14400246" },
    { title: "The Platform", genre: "sci-fi", imdbId: "tt8228288" },
    { title: "The Platform 2", genre: "sci-fi", imdbId: "tt27729779" },
    { title: "Vivarium", genre: "sci-fi", imdbId: "tt8368406" },
    { title: "The Vast of Night", genre: "sci-fi", imdbId: "tt6803046" },
    { title: "The Invisible Man", genre: "sci-fi", imdbId: "tt1051906" },
    { title: "M3GAN", genre: "sci-fi", imdbId: "tt8760708" },
    { title: "M3GAN 2.0", genre: "sci-fi", imdbId: "tt26342662" },
    { title: "The Terminator", genre: "sci-fi", imdbId: "tt0088247" },
    { title: "Terminator 2: Judgment Day", genre: "sci-fi", imdbId: "tt0103064" },
    { title: "Predator", genre: "sci-fi", imdbId: "tt0093773" },
    { title: "Prey", genre: "sci-fi", imdbId: "tt11866324" },
    { title: "The Predator", genre: "sci-fi", imdbId: "tt3829266" },
    { title: "The Host", genre: "sci-fi", imdbId: "tt0468492" },
    { title: "Crimes of the Future", genre: "sci-fi", imdbId: "tt14549466" },
];


// Make available to browser scripts
if (typeof module !== 'undefined') {
    module.exports = horrorMovies;
}